# Generated by Django 5.0.1 on 2024-01-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_thesis_keywords_alter_thesis_sub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='number',
        ),
    ]
