# Generated by Django 5.0.1 on 2024-01-07 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_thesis_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='university',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='panel.university'),
        ),
    ]
